- name: nginx install
  shell: amazon-linux-extras install -y nginx1
  when: not ansible_check_mode

- name: nginx start
  service: 
    name: nginx
    state: started
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"

# - name: change nginx file
#   template:
#     src: roles/nginx/templates/nginx.conf.j2
#     dest: /etc/nginx/conf.d/{{ app }}.conf
#   notify:
#     - restart nginx