- name: Setup nodejs
  shell: curl -sL "{{ node_version }}" | sudo -E bash -

- name: Installing latest version of node.js
  yum:
    name: nodejs
    state: latest
    lock_timeout: 180
  when: not ansible_check_mode

- name: Install yarn package
  get_url:
    url: "https://dl.yarnpkg.com/rpm/yarn.repo"
    dest: /etc/yum.repos.d/yarn.repo

- name: Installing yarn
  yum:
    name: yarn
    state: latest
    lock_timeout: 180
  when: not ansible_check_mode